# path to a directory with all packages
storage: /verdaccio/storage/data
# path to a directory with plugins to include
plugins: /verdaccio/plugins

auth:
  openid-connect:
    publicUrl: http://localhost:4873
    redisUri: redis
    issuer: https://keycloak/auth/realms/MyRealm/
    clientId: verdaccio
    clientSecret: '...'
    usernameClaim: preferred_username
    
    # optional roles claim (id_token).
    # claim can be array or string (comma-separated)
    rolesClaim: roles

web:
  title: Verdaccio
uplinks:
packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
  '**':
    access: $authenticated
    publish: $authenticated
middlewares:
  audit:
    enabled: true
logs:
  - {type: stdout, format: pretty, level: info}
